export const headerText = "Jio Tesseract Developer Platform";
export const topParaText = "Be a part building apps for the future of mixed reality with JioGlass";
export const bannerLink1 = "Start developing";
export const bannerLink2 = "Download Kits"
export const blogHeader = "The immediate Growth";
export const blogPara1 = "India had nearly 700 million internet users across the country. This figure is projected to grow to over 974 million users by 2025. Be a part of this digital growth now.";
export const blogHeader1 = "5G Network Growth";
export const testimonial = "I assure you that Jio will pioneer the 5G revolution in India in the second half of 2021. It will be powered by indigenous-developed network, hardware and technology components";
export const authorName = "Mukesh D. Ambani";
export const blogPara2 = "With a growth in 5G network, the increase of mixed reality experiences will be seamless.";
export const launchProgramHeader = "Jio Glass Launch Program 2021";
export const launchProgramText = "Will be initially launched in June 2021 & then finally to the consumer market by December 2021.";
